server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # React SPA routing (fallback to index.html)
    location / {
        try_files $uri /index.html;
    }

    # Allow global config.json override
    location /config.json {
        add_header Access-Control-Allow-Origin *;
        try_files $uri =404;
    }
}
